var GALLERY = {
    BANNER: "./resources/jsphoto.png",
    IMG_LIST: [
        { uri: './images/31.jpg', title: 'Pacific Coast Highway Sunset' },
        { uri: './images/1.jpg', title: 'Dunne Ranch, Morgan Hill, California' },
        { uri: './images/2.jpg', title: 'Cockpit View' },
        { uri: './images/3.jpg', title: 'Historic Monterey Waterfront' },
        { uri: './images/4.jpg', title: 'Las Vegas Landing' },
        { uri: './images/5.jpg', title: 'Pacific Coast Highway' },
        { uri: './images/6.jpg', title: 'Mt. Tallac Over Tahoe' },
        { uri: './images/7.jpg', title: 'Sentinel Valley Sunset, Yosemite National Park' },
        { uri: './images/8.jpg', title: 'Monterey Fishing Boat' },
        { uri: './images/9.jpg', title: 'Jellyfish' },
        { uri: './images/10.jpg', title: 'Mammoth Hot springs, Yellowstone National Park' },
        { uri: './images/11.jpg', title: 'View From Hoover Dam' },
        { uri: './images/12.jpg', title: 'Hoover Dam Interior' },
        { uri: './images/13.jpg', title: 'Hoover Bridge' },
        { uri: './images/14.jpg', title: 'Las Vegas Strip at Night' },
        { uri: './images/15.jpg', title: 'Alviso Marshland' },
        { uri: './images/16.jpg', title: 'Worn Interior' },
        { uri: './images/17.jpg', title: 'Needs Work' },
        { uri: './images/18.jpg', title: 'Columbia Buildings' },
        { uri: './images/19.jpg', title: 'Haleakala Crater' },
        { uri: './images/20.jpg', title: 'Kaanapali Beach' },
        { uri: './images/21.jpg', title: 'Morgan Hill Field' },
        { uri: './images/22.jpg', title: 'Yellowstone River' },
        { uri: './images/23.jpg', title: 'Morgan Hill Sunset #1' },
        { uri: './images/24.jpg', title: 'Morgan Hill Sunset #2' },
        { uri: './images/25.jpg', title: 'Gardens Pool' },
        { uri: './images/26.jpg', title: 'In For Service' },
        { uri: './images/27.jpg', title: 'Merced River, Yosemite National Park' },
        { uri: './images/28.jpg', title: 'Golden Gate Bridge #1' },
        { uri: './images/29.jpg', title: 'Golden Gate Bridge #2' },
        { uri: './images/30.jpg', title: 'Pacific Coast Highway Cove' },
        { uri: './images/32.jpg', title: 'Monte Carlo, Monaco' },
        { uri: './images/33.jpg', title: 'Monte Carlo Night' },
        { uri: './images/34.jpg', title: 'Steps to the Mediterranean Sea' },
        { uri: './images/35.jpg', title: 'Lake Anderson Sunset, Morgan Hill, California' },
        { uri: './images/36.jpg', title: 'Mission San Antonio' },
        { uri: './images/37.jpg', title: 'Laguna Beach Dusk' },
        { uri: './images/38.jpg', title: 'Laguna Beach Sunset' },
        { uri: './images/39.jpg', title: 'Red Barn in San Martin, California' },
        { uri: './images/40.jpg', title: 'Sentinel Valley, Yosemite National Park' }
    ]
}